export const copy = {
  app: "VerzZify",
  domain: "verzzify.com",
  kicker: "VERZZ",
  tagline: "The house that plays the streets.",
  sub: "Cuts, nights, and rooms — one player, one name.",
  nav: {
    home: "House",
    discover: "Wave",
    library: "Stash",
    community: "Room",
    profile: "You",
    studio: "Booth",
    search: "Find",
    charts: "Heat",
    tickets: "Nights",
  },
  search: "Find a cut, a night, a name…",
  heroKicker: "On the floor",
  waveKicker: "Around your streets",
  houseCuts: "House cuts",
  nightsKicker: "Doors open",
  stashKicker: "Yours offline",
  auth: {
    signIn: "Enter the house",
    signOut: "Leave",
    continueGoogle: "Continue with Google",
    continueX: "Continue with X",
    email: "Email",
    password: "Password",
    name: "Name",
    create: "Make a house pass",
    haveAccount: "Already in",
    needAccount: "New to the house",
  },
} as const;
