-- VerzZify schema bootstrap. Paste into Supabase SQL Editor and click Run.
-- After this succeeds, run infrastructure/supabase/rls.sql


-- ========== 0001_auth.sql ==========

-- Better Auth schema (identity + sessions for "Sign in with Grok").
--
-- Generated by the Better Auth CLI for its Postgres adapter — DO NOT EDIT by
-- hand. `@/lib/auth/server` runs Better Auth against these tables when
-- DATABASE_URL is set. The columns are camelCase and MUST stay double-quoted so
-- Postgres preserves the case Better Auth queries by.
--
-- Migrations in this folder are the single source of truth for your schema. They
-- apply to Neon during the Vercel build (`npm run build`) and to the local
-- PGLite fallback automatically on startup, so dev matches production. Applied
-- files are recorded by name in `_migrations` and NEVER run again.
--
-- Put YOUR app's schema in NEW ordered files (0002_*.sql, 0003_*.sql, …), never
-- in this one. For app tables, prefer snake_case and give per-user tables a
-- `user_id TEXT NOT NULL` column (TEXT, not UUID — the preview dev user id is
-- the string 'dev-user'), then scope every query to the authenticated user
-- server-side (see the `neon` + `auth` skills and src/lib/auth/verify.server.ts).

create table if not exists "user" (
  "id" text not null primary key,
  "name" text not null,
  "email" text not null unique,
  "emailVerified" boolean not null,
  "image" text,
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt" timestamptz default CURRENT_TIMESTAMP not null
);

create table if not exists "session" (
  "id" text not null primary key,
  "expiresAt" timestamptz not null,
  "token" text not null unique,
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt" timestamptz not null,
  "ipAddress" text,
  "userAgent" text,
  "userId" text not null references "user" ("id") on delete cascade
);

create table if not exists "account" (
  "id" text not null primary key,
  "accountId" text not null,
  "providerId" text not null,
  "userId" text not null references "user" ("id") on delete cascade,
  "accessToken" text,
  "refreshToken" text,
  "idToken" text,
  "accessTokenExpiresAt" timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  "scope" text,
  "password" text,
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt" timestamptz not null
);

create table if not exists "verification" (
  "id" text not null primary key,
  "identifier" text not null,
  "value" text not null,
  "expiresAt" timestamptz not null,
  "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
  "updatedAt" timestamptz default CURRENT_TIMESTAMP not null
);

create index if not exists "session_userId_idx" on "session" ("userId");
create index if not exists "account_userId_idx" on "account" ("userId");
create index if not exists "verification_identifier_idx" on "verification" ("identifier");


-- ========== 0002_core.sql ==========

-- VerzZify core schema. Idempotent. No extensions (PGLite + Neon parity).
-- Money is integer minor units (pesewas / cents). Never trust client amounts.

create table if not exists profiles (
  id text primary key,
  username text unique not null,
  display_name text not null,
  role text not null default 'fan',
  country text,
  bio text,
  avatar_url text,
  banner_url text,
  favorite_genres text,
  location_opt_in boolean not null default false,
  city text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists artist_profiles (
  user_id text primary key references profiles(id) on delete cascade,
  artist_name text not null,
  legal_name text,
  verification_status text not null default 'unverified',
  monthly_listeners integer not null default 0,
  biography text,
  socials text,
  payout_ready boolean not null default false,
  genres text,
  created_at timestamptz not null default now()
);

create table if not exists artist_verification (
  id text primary key,
  artist_id text not null references artist_profiles(user_id) on delete cascade,
  status text not null default 'pending',
  notes text,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists genres (
  id text primary key,
  name text not null,
  slug text unique not null
);

create table if not exists albums (
  id text primary key,
  artist_id text not null references artist_profiles(user_id),
  title text not null,
  description text,
  cover_url text not null,
  release_date date,
  album_type text not null default 'album',
  price_cents integer not null default 0,
  currency text not null default 'GHS',
  visibility text not null default 'public'
);

create table if not exists tracks (
  id text primary key,
  artist_id text not null references artist_profiles(user_id),
  album_id text references albums(id),
  title text not null,
  cover_url text not null,
  audio_url text not null,
  duration_ms integer not null default 0,
  genre text,
  subgenre text,
  language text,
  distribution text not null default 'free_stream',
  price_cents integer not null default 0,
  currency text not null default 'GHS',
  explicit boolean not null default false,
  isrc text,
  lyrics text,
  copyright_owner text,
  featured_artists text,
  producer text,
  songwriter text,
  status text not null default 'published',
  play_count integer not null default 0,
  like_count integer not null default 0,
  sort_order integer not null default 0,
  country text,
  created_at timestamptz not null default now()
);

create table if not exists track_genres (
  track_id text not null references tracks(id) on delete cascade,
  genre_id text not null references genres(id),
  primary key (track_id, genre_id)
);

create table if not exists playlists (
  id text primary key,
  user_id text not null references profiles(id) on delete cascade,
  title text not null,
  description text,
  cover_url text,
  is_public boolean not null default true,
  is_system boolean not null default false,
  kind text not null default 'custom',
  created_at timestamptz not null default now()
);

create table if not exists playlist_tracks (
  playlist_id text not null references playlists(id) on delete cascade,
  track_id text not null references tracks(id) on delete cascade,
  position integer not null default 0,
  primary key (playlist_id, track_id)
);

create table if not exists favorites (
  user_id text not null references profiles(id) on delete cascade,
  target_type text not null,
  target_id text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, target_type, target_id)
);

create table if not exists follows (
  follower_id text not null references profiles(id) on delete cascade,
  following_id text not null references profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id)
);

create table if not exists listening_history (
  id text primary key,
  user_id text not null references profiles(id) on delete cascade,
  track_id text not null references tracks(id) on delete cascade,
  played_at timestamptz not null default now(),
  duration_ms integer not null default 0,
  completed boolean not null default false
);

create table if not exists stream_events (
  id text primary key,
  user_id text,
  track_id text not null references tracks(id) on delete cascade,
  device_hash text,
  started_at timestamptz not null default now(),
  listened_ms integer not null default 0,
  meaningful boolean not null default false
);

create table if not exists commission_rules (
  id text primary key,
  product_type text not null,
  platform_bps integer not null,
  processor_bps integer not null default 0,
  min_payout_cents integer not null default 0,
  currency text not null default 'GHS'
);

create table if not exists purchases (
  id text primary key,
  buyer_id text not null references profiles(id),
  status text not null default 'completed',
  currency text not null,
  gross_cents integer not null,
  processor_fee_cents integer not null,
  platform_fee_cents integer not null,
  creator_cents integer not null,
  fee_snapshot text not null,
  created_at timestamptz not null default now()
);

create table if not exists purchase_items (
  id text primary key,
  purchase_id text not null references purchases(id) on delete cascade,
  item_type text not null,
  item_id text not null,
  title text not null,
  price_cents integer not null
);

create table if not exists licenses (
  id text primary key,
  purchase_id text not null references purchases(id),
  user_id text not null references profiles(id),
  track_id text not null references tracks(id),
  license_type text not null,
  rights_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists wallets (
  user_id text primary key references profiles(id) on delete cascade,
  currency text not null default 'GHS',
  created_at timestamptz not null default now()
);

create table if not exists ledger_entries (
  id text primary key,
  wallet_user_id text not null references wallets(user_id),
  amount_cents integer not null,
  direction text not null,
  kind text not null,
  ref_type text,
  ref_id text,
  available boolean not null default true,
  meta text,
  created_at timestamptz not null default now()
);

create table if not exists payout_requests (
  id text primary key,
  artist_id text not null references artist_profiles(user_id),
  amount_cents integer not null,
  currency text not null default 'GHS',
  method text not null,
  destination text,
  status text not null default 'requested',
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists payment_transactions (
  id text primary key,
  user_id text not null,
  provider text not null,
  provider_ref text,
  amount_cents integer not null,
  currency text not null,
  status text not null,
  purpose text not null,
  created_at timestamptz not null default now()
);

create table if not exists subscription_plans (
  id text primary key,
  name text not null,
  price_cents integer not null,
  currency text not null default 'GHS',
  interval text not null default 'month',
  features text
);

create table if not exists subscriptions (
  user_id text not null references profiles(id) on delete cascade,
  plan_id text not null references subscription_plans(id),
  status text not null default 'active',
  current_period_end timestamptz,
  primary key (user_id, plan_id)
);

create table if not exists events (
  id text primary key,
  organizer_id text not null references profiles(id),
  title text not null,
  poster_url text not null,
  venue text,
  city text,
  country text,
  starts_at timestamptz not null,
  ends_at timestamptz,
  description text,
  status text not null default 'published'
);

create table if not exists event_ticket_types (
  id text primary key,
  event_id text not null references events(id) on delete cascade,
  name text not null,
  price_cents integer not null,
  currency text not null default 'GHS',
  capacity integer not null default 100,
  sold integer not null default 0
);

create table if not exists tickets (
  id text primary key,
  ticket_type_id text not null references event_ticket_types(id),
  event_id text not null references events(id),
  buyer_id text not null references profiles(id),
  code text unique not null,
  qr_payload text not null,
  status text not null default 'valid',
  created_at timestamptz not null default now()
);

create table if not exists ticket_scans (
  id text primary key,
  ticket_id text not null references tickets(id),
  scanner_user_id text,
  result text not null,
  scanned_at timestamptz not null default now()
);

create table if not exists live_events (
  id text primary key,
  artist_id text not null references artist_profiles(user_id),
  title text not null,
  poster_url text not null,
  description text,
  starts_at timestamptz not null,
  price_cents integer not null default 0,
  is_free boolean not null default false,
  capacity integer,
  status text not null default 'scheduled'
);

create table if not exists live_entitlements (
  user_id text not null references profiles(id) on delete cascade,
  live_event_id text not null references live_events(id) on delete cascade,
  purchased_at timestamptz not null default now(),
  primary key (user_id, live_event_id)
);

create table if not exists video_call_services (
  artist_id text primary key references artist_profiles(user_id),
  duration_min integer not null default 15,
  price_cents integer not null,
  currency text not null default 'GHS',
  available boolean not null default true
);

create table if not exists bookings (
  id text primary key,
  artist_id text not null references artist_profiles(user_id),
  fan_id text not null references profiles(id),
  starts_at timestamptz not null,
  duration_min integer not null,
  price_cents integer not null,
  currency text not null default 'GHS',
  status text not null default 'confirmed'
);

create table if not exists posts (
  id text primary key,
  user_id text not null references profiles(id) on delete cascade,
  body text not null,
  image_url text,
  track_id text references tracks(id),
  event_id text references events(id),
  like_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists comments (
  id text primary key,
  user_id text not null references profiles(id) on delete cascade,
  target_type text not null,
  target_id text not null,
  parent_id text,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists conversations (
  id text primary key,
  created_at timestamptz not null default now()
);

create table if not exists conversation_members (
  conversation_id text not null references conversations(id) on delete cascade,
  user_id text not null references profiles(id) on delete cascade,
  primary key (conversation_id, user_id)
);

create table if not exists messages (
  id text primary key,
  conversation_id text not null references conversations(id) on delete cascade,
  sender_id text not null references profiles(id),
  body text not null,
  image_url text,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create table if not exists notifications (
  id text primary key,
  user_id text not null references profiles(id) on delete cascade,
  category text not null,
  title text not null,
  body text,
  link text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists device_tokens (
  id text primary key,
  user_id text not null references profiles(id) on delete cascade,
  token text not null,
  platform text not null
);

create table if not exists reports (
  id text primary key,
  reporter_id text not null references profiles(id),
  target_type text not null,
  target_id text not null,
  reason text not null,
  status text not null default 'open',
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists copyright_claims (
  id text primary key,
  track_id text not null references tracks(id),
  claimant_name text not null,
  details text,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

create table if not exists admin_actions (
  id text primary key,
  admin_id text not null,
  action text not null,
  target_type text,
  target_id text,
  meta text,
  created_at timestamptz not null default now()
);

create table if not exists analytics_events (
  id text primary key,
  user_id text,
  name text not null,
  props text,
  created_at timestamptz not null default now()
);

create table if not exists feature_flags (
  key text primary key,
  enabled boolean not null default true,
  payload text
);

create table if not exists remote_config (
  key text primary key,
  value text not null
);

create table if not exists articles (
  id text primary key,
  title text not null,
  slug text unique not null,
  category text not null,
  excerpt text,
  body text not null,
  cover_url text,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists search_log (
  id text primary key,
  user_id text,
  query text not null,
  created_at timestamptz not null default now()
);

create index if not exists tracks_artist_idx on tracks (artist_id);
create index if not exists tracks_genre_idx on tracks (genre);
create index if not exists tracks_status_idx on tracks (status);
create index if not exists tracks_play_idx on tracks (play_count desc);
create index if not exists albums_artist_idx on albums (artist_id);
create index if not exists history_user_idx on listening_history (user_id, played_at desc);
create index if not exists stream_track_idx on stream_events (track_id, started_at desc);
create index if not exists ledger_wallet_idx on ledger_entries (wallet_user_id, created_at desc);
create index if not exists posts_created_idx on posts (created_at desc);
create index if not exists comments_target_idx on comments (target_type, target_id);
create index if not exists notifications_user_idx on notifications (user_id, created_at desc);
create index if not exists events_starts_idx on events (starts_at);
create index if not exists favorites_target_idx on favorites (target_type, target_id);


-- ========== 0002_sheba.sql ==========

-- Stub: old filename kept so stale Vite globs do not 500.
select 1;


-- ========== 0003_seed.sql ==========

-- Catalog seed. Fictional artists. Replay-safe via ON CONFLICT.

insert into genres (id, name, slug) values
  ('g_hiphop','Hip Hop','hip-hop'),
  ('g_rnb','R&B','rnb'),
  ('g_pop','Pop','pop'),
  ('g_afrobeats','Afrobeats','afrobeats'),
  ('g_gospel','Gospel','gospel'),
  ('g_reggae','Reggae','reggae'),
  ('g_dancehall','Dancehall','dancehall'),
  ('g_amapiano','Amapiano','amapiano'),
  ('g_highlife','Highlife','highlife'),
  ('g_hiplife','Hiplife','hiplife'),
  ('g_electronic','Electronic','electronic'),
  ('g_latin','Latin','latin'),
  ('g_indie','Indie','indie'),
  ('g_fusion','Afro-fusion','afro-fusion'),
  ('g_blues','Desert Blues','desert-blues')
on conflict (id) do nothing;

insert into profiles (id, username, display_name, role, country, bio, avatar_url, banner_url, city) values
  ('sys_zelyro','verzzify','VerzZify','admin','US','The VerzZify editorial desk.','/favicon.svg','/banners/hero.jpg','New York'),
  ('sys_ama','ama-serwaa','Ama Serwaa','artist','GH','Highlife for the golden hour.','/artists/ama.jpg','/banners/accra.jpg','Accra'),
  ('sys_kofi','kofi-blade','Kofi Blade','artist','GB','UK rap from the Hackney night market.','/artists/kofi.jpg','/banners/accra.jpg','London'),
  ('sys_nia','nia-adaeze','Nia Adaeze','artist','NG','Afrobeats, rain, and rooftop marble.','/artists/nia.jpg','/banners/lagos.jpg','Lagos'),
  ('sys_sefu','sefu-diallo','Sefu Diallo','artist','SN','Guitar at the edge of the Atlantic.','/artists/sefu.jpg','/banners/accra.jpg','Dakar'),
  ('sys_wave','accra-wave','The Accra Wave','artist','GH','Amapiano warehouse nights.','/artists/accra-wave.jpg','/banners/accra.jpg','Accra'),
  ('sys_adwoa','sister-adwoa','Sister Adwoa','artist','US','Gospel that sounds like morning light.','/artists/adwoa.jpg','/banners/chapel.jpg','Atlanta'),
  ('sys_yaw','yaw-lion','Yaw Lion','artist','JM','Dancehall from the Kingston rooftop.','/artists/yaw.jpg','/banners/accra.jpg','Kingston'),
  ('sys_lila','lila-moyo','Lila Moyo','artist','ZA','Amapiano in jacaranda season.','/artists/lila.jpg','/banners/lagos.jpg','Johannesburg'),
  ('sys_ebo','ebo-darko','Ebo Darko','producer','US','Bars and analog desks.','/artists/ebo.jpg','/banners/accra.jpg','New York'),
  ('sys_zainab','zainab-keita','Zainab Keita','artist','ML','Desert blues, dawn dust.','/artists/zainab.jpg','/banners/chapel.jpg','Bamako')
on conflict (id) do nothing;

insert into artist_profiles (user_id, artist_name, legal_name, verification_status, monthly_listeners, biography, genres, payout_ready) values
  ('sys_ama','Ama Serwaa','Ama Serwaa Mensah','verified',842000,'Ama writes highlife the way Accra remembers itself — brass, patience, and a voice that does not hurry.','Highlife',true),
  ('sys_kofi','Kofi Blade','Kofi Owusu','verified',510000,'Hackney night-market rap. Tight drums, punchlines, neon on wet tar.','Hip Hop',true),
  ('sys_nia','Nia Adaeze','Nia Adaeze Okonkwo','verified',1200000,'Lagos after rain. Afrobeats that sit between club and confession.','Afrobeats',true),
  ('sys_sefu','Sefu Diallo','Sefu Diallo','pending',188000,'Wolof guitar lines against the Atlantic wind.','Afro-fusion',false),
  ('sys_wave','The Accra Wave','Accra Wave Collective','verified',390000,'Three selectors, one warehouse, copper light until dawn.','Amapiano',true),
  ('sys_adwoa','Sister Adwoa','Adwoa Nyarko','verified',276000,'Gospel from Atlanta — linen, stained glass, unshaken hope.','Gospel',true),
  ('sys_yaw','Yaw Lion','Yaw Boateng','unverified',154000,'Dancehall from Kingston. Rooftop fire, no apology.','Dancehall',false),
  ('sys_lila','Lila Moyo','Lila Moyo','verified',670000,'Johannesburg amapiano with a quiet centre.','Amapiano',true),
  ('sys_ebo','Ebo Darko','Ebo Darko','pending',98000,'Producer, writer, occasional verse. The Brooklyn desk is the instrument.','Hip Hop',false),
  ('sys_zainab','Zainab Keita','Zainab Keita','verified',221000,'A single guitar and the first light over Bamako.','Desert Blues',true)
on conflict (user_id) do nothing;

insert into albums (id, artist_id, title, description, cover_url, release_date, album_type, price_cents, currency) values
  ('alb_gold','sys_ama','Gold Coast Evening','Two highlife studies for Accra at dusk.','/covers/gold-coast.jpg','2026-03-12','album',2500,'GHS'),
  ('alb_terrace','sys_nia','Terrace Lights','Afrobeats from a wet Lagos terrace.','/covers/terrace-lights.jpg','2026-05-02','ep',1800,'NGN'),
  ('alb_ware','sys_wave','Warehouse 04','Amapiano recorded live off the CDJs.','/covers/warehouse.jpg','2026-04-18','album',2000,'GHS'),
  ('alb_night','sys_kofi','Night Market','A London single cycle.','/covers/night-market.jpg','2026-06-01','single',399,'GBP'),
  ('alb_atl','sys_sefu','Atlantic Wind','Guitar and salt air.','/covers/atlantic-wind.jpg','2026-02-20','single',0,'USD'),
  ('alb_mercy','sys_adwoa','Morning Mercy','A Sunday that lasts all week.','/covers/morning-mercy.jpg','2026-01-11','single',0,'USD'),
  ('alb_roof','sys_yaw','Rooftop Fire','Dancehall, no water.','/covers/rooftop-fire.jpg','2026-07-08','single',399,'USD'),
  ('alb_jac','sys_lila','Jacaranda','Amapiano in bloom.','/covers/jacaranda.jpg','2026-03-30','single',900,'ZAR'),
  ('alb_desk','sys_ebo','Desk Light','Late sessions, analog board.','/covers/desk-light.jpg','2026-05-22','single',299,'USD'),
  ('alb_dawn','sys_zainab','Dawn Dust','First light, one guitar.','/covers/dawn-dust.jpg','2026-04-04','single',0,'USD')
on conflict (id) do nothing;

insert into tracks (
  id, artist_id, album_id, title, cover_url, audio_url, duration_ms, genre, language,
  distribution, price_cents, currency, copyright_owner, producer, songwriter, play_count, like_count, sort_order, country, status
) values
  ('trk_01','sys_ama','alb_gold','Gold Coast Evening','/covers/gold-coast.jpg','/audio/t01.mp3',75000,'Highlife','Twi','paid_download',800,'GHS','Ama Serwaa','Kwame Boat','Ama Serwaa',184200,4120,1,'GH','published'),
  ('trk_02','sys_ama','alb_gold','Brass at Dusk','/covers/gold-coast.jpg','/audio/t02.mp3',75000,'Highlife','Twi','free_stream',0,'GHS','Ama Serwaa','Kwame Boat','Ama Serwaa',121400,2880,2,'GH','published'),
  ('trk_03','sys_kofi','alb_night','Night Market','/covers/night-market.jpg','/audio/t03.mp3',75000,'Hip Hop','English','paid_download',399,'GBP','Kofi Blade','Ebo Darko','Kofi Blade',98000,2104,1,'GB','published'),
  ('trk_04','sys_nia','alb_terrace','Rain on Marble','/covers/terrace-lights.jpg','/audio/t04.mp3',75000,'Afrobeats','English','premium',1200,'NGN','Nia Adaeze','Nia Adaeze','Nia Adaeze',402100,8900,1,'NG','published'),
  ('trk_05','sys_nia','alb_terrace','Terrace','/covers/terrace-lights.jpg','/audio/t05.mp3',75000,'Afrobeats','English','free_stream',0,'NGN','Nia Adaeze','Nia Adaeze','Nia Adaeze',255000,5400,2,'NG','published'),
  ('trk_06','sys_sefu','alb_atl','Atlantic Wind','/covers/atlantic-wind.jpg','/audio/t06.mp3',75000,'Afro-fusion','Wolof','free_download',0,'USD','Sefu Diallo','Sefu Diallo','Sefu Diallo',64000,1802,1,'SN','published'),
  ('trk_07','sys_wave','alb_ware','Warehouse 04','/covers/warehouse.jpg','/audio/t07.mp3',75000,'Amapiano','English','paid_download',700,'GHS','The Accra Wave','The Accra Wave','The Accra Wave',173000,3301,1,'GH','published'),
  ('trk_08','sys_adwoa','alb_mercy','Morning Mercy','/covers/morning-mercy.jpg','/audio/t08.mp3',75000,'Gospel','English','free_download',0,'USD','Sister Adwoa','Sister Adwoa','Sister Adwoa',91000,2700,1,'US','published'),
  ('trk_09','sys_yaw','alb_roof','Rooftop Fire','/covers/rooftop-fire.jpg','/audio/t09.mp3',75000,'Dancehall','English','paid_download',399,'USD','Yaw Lion','Ebo Darko','Yaw Lion',77000,1540,1,'JM','published'),
  ('trk_10','sys_lila','alb_jac','Jacaranda','/covers/jacaranda.jpg','/audio/t10.mp3',75000,'Amapiano','English','paid_download',900,'ZAR','Lila Moyo','Lila Moyo','Lila Moyo',210400,4980,1,'ZA','published'),
  ('trk_11','sys_ebo','alb_desk','Desk Light','/covers/desk-light.jpg','/audio/t11.mp3',75000,'Hip Hop','English','free_stream',0,'USD','Ebo Darko','Ebo Darko','Ebo Darko',45000,980,1,'US','published'),
  ('trk_12','sys_zainab','alb_dawn','Dawn Dust','/covers/dawn-dust.jpg','/audio/t12.mp3',75000,'Desert Blues','Bambara','free_download',0,'USD','Zainab Keita','Zainab Keita','Zainab Keita',88000,2400,1,'ML','published')
on conflict (id) do nothing;

insert into playlists (id, user_id, title, description, cover_url, is_public, is_system, kind) values
  ('pl_ghana','sys_zelyro','Global Charts','What the catalog is holding this week.','/covers/gold-coast.jpg',true,true,'editorial'),
  ('pl_afro','sys_zelyro','Afrobeats Now','Current pulse.','/covers/terrace-lights.jpg',true,true,'editorial'),
  ('pl_sunday','sys_zelyro','Sunday Light','Gospel and quiet morning records.','/covers/morning-mercy.jpg',true,true,'editorial'),
  ('pl_piano','sys_zelyro','After Dark','Warehouse to balcony.','/covers/warehouse.jpg',true,true,'editorial'),
  ('pl_free','sys_zelyro','Free Downloads','Creator-authorized free files.','/covers/atlantic-wind.jpg',true,true,'editorial'),
  ('pl_hip','sys_zelyro','Hip Hop Desk','Late rooms, analog boards, city nights.','/covers/desk-light.jpg',true,true,'editorial')
on conflict (id) do nothing;

insert into playlist_tracks (playlist_id, track_id, position) values
  ('pl_ghana','trk_01',1),('pl_ghana','trk_04',2),('pl_ghana','trk_03',3),('pl_ghana','trk_07',4),('pl_ghana','trk_10',5),('pl_ghana','trk_11',6),
  ('pl_afro','trk_04',1),('pl_afro','trk_05',2),('pl_afro','trk_10',3),('pl_afro','trk_07',4),
  ('pl_sunday','trk_08',1),('pl_sunday','trk_12',2),('pl_sunday','trk_02',3),
  ('pl_piano','trk_07',1),('pl_piano','trk_10',2),('pl_piano','trk_05',3),
  ('pl_free','trk_06',1),('pl_free','trk_08',2),('pl_free','trk_12',3),
  ('pl_hip','trk_11',1),('pl_hip','trk_03',2),('pl_hip','trk_09',3)
on conflict do nothing;

insert into events (id, organizer_id, title, poster_url, venue, city, country, starts_at, description, status) values
  ('evt_labadi','sys_ama','Labadi Highlife Night','/events/labadi.jpg','Labadi Beach','Accra','GH','2026-09-12 19:00:00+00','Sunset brass, sand, and the Gold Coast catalog live.','published'),
  ('evt_ware','sys_wave','Warehouse 04 — Live','/covers/warehouse.jpg','Tema Industrial Shed 4','Accra','GH','2026-08-29 22:00:00+00','Amapiano until the copper lights fail.','published'),
  ('evt_east','sys_ebo','East River Session','/covers/desk-light.jpg','Bushwick Room','New York','US','2026-09-05 21:00:00+00','Analog desk, late verses, East River after midnight.','published'),
  ('evt_hackney','sys_kofi','Hackney Night Market','/covers/night-market.jpg','Netil Market','London','GB','2026-09-18 20:00:00+00','UK rap under the railway lights.','published')
on conflict (id) do nothing;

insert into event_ticket_types (id, event_id, name, price_cents, currency, capacity, sold) values
  ('tt_lab_std','evt_labadi','Standard',8000,'GHS',800,214),
  ('tt_lab_vip','evt_labadi','VIP',20000,'GHS',120,41),
  ('tt_ware_std','evt_ware','Standard',6000,'GHS',400,188),
  ('tt_east_std','evt_east','Standard',3500,'USD',300,92),
  ('tt_hack_std','evt_hackney','Standard',1800,'GBP',250,67)
on conflict (id) do nothing;

insert into live_events (id, artist_id, title, poster_url, description, starts_at, price_cents, is_free, capacity, status) values
  ('live_nia','sys_nia','Terrace Lights — VerzZify Live','/events/rooftop.jpg','An intimate Lagos rooftop set. PPV access, server-validated.','2026-08-22 20:00:00+00',2500,false,500,'scheduled'),
  ('live_adwoa','sys_adwoa','Morning Mercy — Chapel Session','/covers/morning-mercy.jpg','A free Sunday livestream from Atlanta.','2026-08-23 09:00:00+00',0,true,null,'scheduled')
on conflict (id) do nothing;

insert into video_call_services (artist_id, duration_min, price_cents, currency, available) values
  ('sys_ama',15,15000,'GHS',true),
  ('sys_nia',10,22000,'NGN',true),
  ('sys_kofi',15,2500,'GBP',true)
on conflict (artist_id) do nothing;

insert into posts (id, user_id, body, image_url, track_id, like_count, created_at) values
  ('post_1','sys_ama','Gold Coast Evening is out. Brass, dusk, and the city below. Thank you for sitting with this one.','/covers/gold-coast.jpg','trk_01',842, now() - interval '2 days'),
  ('post_2','sys_nia','Rooftop session this week on VerzZify Live. Bring a quiet evening.','/events/rooftop.jpg','trk_04',1204, now() - interval '1 day'),
  ('post_3','sys_wave','Warehouse 04. Doors 10. No phones on the booth.','/covers/warehouse.jpg','trk_07',511, now() - interval '18 hours'),
  ('post_4','sys_adwoa','If you need a Sunday that does not rush you, Morning Mercy is free to keep.','/covers/morning-mercy.jpg','trk_08',390, now() - interval '3 days'),
  ('post_5','sys_kofi','Night market never closed. New single in the library.','/covers/night-market.jpg','trk_03',276, now() - interval '8 hours'),
  ('post_6','sys_zainab','Recorded at first light. The guitar stayed in one take.','/covers/dawn-dust.jpg','trk_12',188, now() - interval '5 days')
on conflict (id) do nothing;

insert into comments (id, user_id, target_type, target_id, body) values
  ('c_1','sys_kofi','track','trk_01','The brass line at 0:40 is unfair.'),
  ('c_2','sys_ebo','track','trk_04','Mix is clean. Vocal sits right.')
on conflict (id) do nothing;

insert into articles (id, title, slug, category, excerpt, body, cover_url) values
  ('art_1','Highlife does not need to shout','highlife-does-not-shout','Music','Ama Serwaa and the quiet return of Accra brass.','VerzZify is not a copy of anyone’s catalog. The Gold Coast Evening sessions were tracked at dusk so the horns would have to compete with the city, not a click.','/covers/gold-coast.jpg'),
  ('art_2','How artists keep the file','how-artists-keep-the-file','Artists','Why VerzZify sells downloads without selling the copyright.','A purchase on VerzZify is a license the artist wrote. Basic keeps the file in your account. Premium, when the artist allows it, is an authorized download with a receipt. Copyright does not move.','/covers/desk-light.jpg')
on conflict (id) do nothing;

insert into commission_rules (id, product_type, platform_bps, processor_bps, min_payout_cents, currency) values
  ('fee_track','track',1500,300,5000,'USD'),
  ('fee_ticket','ticket',1000,300,5000,'USD'),
  ('fee_live','live',1200,300,5000,'USD'),
  ('fee_call','video_call',1500,300,5000,'USD')
on conflict (id) do nothing;

insert into subscription_plans (id, name, price_cents, currency, interval, features) values
  ('plan_free','VerzZify Free',0,'USD','month','Standard streaming, discovery, community'),
  ('plan_plus','VerzZify Plus',999,'USD','month','Ad-free VerzZify-hosted audio, extra downloads, early live access')
on conflict (id) do nothing;

insert into feature_flags (key, enabled, payload) values
  ('ENABLE_YOUTUBE',true,null),
  ('ENABLE_TICKETING',true,null),
  ('ENABLE_VERZZIFY_LIVE',true,null),
  ('ENABLE_VIDEO_CALLS',true,null),
  ('ENABLE_PREMIUM',true,null),
  ('ENABLE_NEARBY_ARTISTS',true,null)
on conflict (key) do nothing;

insert into remote_config (key, value) values
  ('default_currency','USD'),
  ('supported_currencies','USD,GBP,EUR,GHS,NGN,ZAR'),
  ('min_payout_cents','5000'),
  ('maintenance_mode','false')
on conflict (key) do nothing;

insert into wallets (user_id, currency) values
  ('sys_ama','GHS'),('sys_kofi','GBP'),('sys_nia','NGN'),('sys_sefu','USD'),
  ('sys_wave','GHS'),('sys_adwoa','USD'),('sys_yaw','USD'),('sys_lila','ZAR'),
  ('sys_ebo','USD'),('sys_zainab','USD')
on conflict (user_id) do nothing;

insert into ledger_entries (id, wallet_user_id, amount_cents, direction, kind, ref_type, available, meta) values
  ('led_ama_1','sys_ama',184200,'credit','sale','track',true,'{"note":"lifetime seed"}'),
  ('led_ama_2','sys_ama',42000,'credit','sale','ticket',false,'{"note":"pending settlement"}'),
  ('led_nia_1','sys_nia',512000,'credit','sale','track',true,'{"note":"lifetime seed"}'),
  ('led_wave_1','sys_wave',91000,'credit','sale','ticket',true,'{"note":"lifetime seed"}')
on conflict (id) do nothing;


-- ========== 0004_youtube_promotions.sql ==========

-- YouTube promotion, external music links, nearby studios.
-- DJ is not an account type: existing DJ profiles become artists.

update profiles set role = 'artist' where role = 'dj';

create table if not exists youtube_connections (
  artist_id text primary key references artist_profiles(user_id) on delete cascade,
  channel_id text not null,
  channel_url text not null,
  channel_name text not null,
  avatar_url text,
  subscriber_count integer,
  connected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists external_music_links (
  id text primary key,
  artist_id text not null references artist_profiles(user_id) on delete cascade,
  provider text not null,
  external_url text not null,
  external_content_id text,
  title text,
  thumbnail_url text,
  channel_name text,
  channel_id text,
  description text,
  published_at timestamptz,
  duration_seconds integer,
  category text not null default 'music_video',
  is_featured boolean not null default false,
  is_promoted boolean not null default false,
  embeddable boolean not null default true,
  public_stats text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists promotion_campaigns (
  id text primary key,
  creator_id text not null references profiles(id),
  content_type text not null,
  content_id text,
  external_music_link_id text references external_music_links(id),
  campaign_name text not null,
  description text,
  status text not null default 'draft',
  budget_cents integer not null default 0,
  daily_budget_cents integer not null default 0,
  spent_cents integer not null default 0,
  currency text not null default 'GHS',
  start_date date,
  end_date date,
  target_countries text,
  target_genres text,
  target_audience text,
  rejection_reason text,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists promotion_targets (
  id text primary key,
  campaign_id text not null references promotion_campaigns(id) on delete cascade,
  target_type text not null,
  target_value text not null
);

create table if not exists promotion_impressions (
  id text primary key,
  campaign_id text not null references promotion_campaigns(id) on delete cascade,
  user_id text,
  created_at timestamptz not null default now()
);

create table if not exists promotion_clicks (
  id text primary key,
  campaign_id text not null references promotion_campaigns(id) on delete cascade,
  user_id text,
  kind text not null default 'card',
  created_at timestamptz not null default now()
);

create table if not exists promotion_engagement (
  id text primary key,
  campaign_id text not null references promotion_campaigns(id) on delete cascade,
  user_id text,
  event_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists producer_profiles (
  user_id text primary key references profiles(id) on delete cascade,
  display_title text,
  beats text,
  portfolio text,
  services text,
  credits text,
  location text,
  available_for_collab boolean not null default true,
  socials text,
  youtube_url text,
  contact text
);

create table if not exists studios (
  id text primary key,
  name text not null,
  city text,
  country text,
  kind text not null default 'recording',
  description text
);

create index if not exists eml_artist_idx on external_music_links (artist_id);
create index if not exists eml_provider_idx on external_music_links (provider);
create index if not exists eml_content_idx on external_music_links (external_content_id);
create index if not exists promo_status_idx on promotion_campaigns (status, start_date);
create index if not exists promo_creator_idx on promotion_campaigns (creator_id);
create index if not exists promo_imp_idx on promotion_impressions (campaign_id, created_at);
create index if not exists promo_click_idx on promotion_clicks (campaign_id, created_at);
create index if not exists promo_eng_idx on promotion_engagement (campaign_id, created_at);

-- Producer extras (Ebo already has an artist_profiles row for catalog work).
insert into producer_profiles (user_id, display_title, beats, services, credits, location, available_for_collab, youtube_url, contact)
values (
  'sys_ebo',
  'Analog desk, UK bars, night-market drums',
  'Hip hop kits, live brass stems, voice notes',
  'Beat lease, mix, feature verse',
  'Kofi Blade — Night Market; Yaw Lion — Rooftop Fire',
  'New York',
  true,
  'https://youtube.com/@verzzify',
  'studio@verzzify.com'
) on conflict (user_id) do nothing;

insert into studios (id, name, city, country, kind, description) values
  ('st_labadi', 'Labadi Tape Room', 'Accra', 'GH', 'recording', 'Seaside booth, analog board.'),
  ('st_ikeja', 'Ikeja Terrace Studio', 'Lagos', 'NG', 'recording', 'Tracking rooms, wet terrace after rain.'),
  ('st_hackney', 'Hackney Night Desk', 'London', 'GB', 'recording', 'Late sessions under the overground.'),
  ('st_bushwick', 'Bushwick Room', 'New York', 'US', 'recording', 'Analog board, East River after midnight.'),
  ('st_kingston', 'Harbour Light', 'Kingston', 'JM', 'recording', 'Rooftop dancehall, no water.')
on conflict (id) do nothing;

-- Official YouTube videos promoted inside VerzZify. Metadata is stored so the
-- catalog works without a Data API key; playback always uses YouTube itself.
insert into external_music_links (
  id, artist_id, provider, external_url, external_content_id, title, thumbnail_url,
  channel_name, channel_id, description, duration_seconds, category, is_featured, is_promoted, embeddable
) values
  (
    'eml_kwaku', 'sys_ama', 'youtube',
    'https://www.youtube.com/watch?v=GIDiI5kyBDQ', 'GIDiI5kyBDQ',
    'Black Sherif - Kwaku the Traveller (Official Video)',
    'https://i.ytimg.com/vi/GIDiI5kyBDQ/hqdefault.jpg',
    'Black Sherif Music', 'UCKfrbVDBEq-wcYC4rUzEosA',
    'Official video. VerzZify does not host this file.',
    213, 'music_video', true, true, true
  ),
  (
    'eml_terminator', 'sys_kofi', 'youtube',
    'https://www.youtube.com/watch?v=NPCC02SaJVg', 'NPCC02SaJVg',
    'King Promise - Terminator feat. Young Jonn (Official Video)',
    'https://i.ytimg.com/vi/NPCC02SaJVg/hqdefault.jpg',
    'King Promise Official', 'UCHhS8FHRTxM7ysMKRUl3LHQ',
    'Official video. VerzZify does not host this file.',
    244, 'music_video', true, true, true
  ),
  (
    'eml_lastlast', 'sys_nia', 'youtube',
    'https://www.youtube.com/watch?v=421w1j87fEM', '421w1j87fEM',
    'Burna Boy - Last Last [Official Music Video]',
    'https://i.ytimg.com/vi/421w1j87fEM/hqdefault.jpg',
    'Burna Boy', 'UCEzDdNqNkT-7rSfSGSr1hWg',
    'Official video. VerzZify does not host this file.',
    174, 'music_video', true, true, true
  ),
  (
    'eml_tanzania', 'sys_lila', 'youtube',
    'https://www.youtube.com/watch?v=WvxADzZMkEI', 'WvxADzZMkEI',
    'Uncle Waffles and Tony Duardo - Tanzania (Official Music Video)',
    'https://i.ytimg.com/vi/WvxADzZMkEI/hqdefault.jpg',
    'Uncle Waffles', 'UCDfH7E8iHkEjmZ6H9uQ5o1g',
    'Official video. VerzZify does not host this file.',
    236, 'music_video', true, true, true
  ),
  (
    'eml_warehouseyt', 'sys_wave', 'youtube',
    'https://www.youtube.com/watch?v=WvxADzZMkEI', 'WvxADzZMkEI',
    'Uncle Waffles and Tony Duardo - Tanzania (Official Music Video)',
    'https://i.ytimg.com/vi/WvxADzZMkEI/hqdefault.jpg',
    'Uncle Waffles', 'UCDfH7E8iHkEjmZ6H9uQ5o1g',
    'Amapiano night, official YouTube. VerzZify does not host this file.',
    236, 'performance', true, true, true
  ),
  (
    'eml_freemind', 'sys_nia', 'youtube',
    'https://www.youtube.com/watch?v=tQiNQL-FEgU', 'tQiNQL-FEgU',
    'Free Mind',
    'https://i.ytimg.com/vi/tQiNQL-FEgU/hqdefault.jpg',
    'Tems', 'UCXg6YtKpgC59gRKUfxQw8Fw',
    'Official audio on YouTube.',
    248, 'latest', true, false, true
  )
on conflict (id) do nothing;

insert into youtube_connections (artist_id, channel_id, channel_url, channel_name, subscriber_count)
values
  ('sys_ama', 'UCKfrbVDBEq-wcYC4rUzEosA', 'https://www.youtube.com/channel/UCKfrbVDBEq-wcYC4rUzEosA', 'Black Sherif Music', 2400000),
  ('sys_nia', 'UCEzDdNqNkT-7rSfSGSr1hWg', 'https://www.youtube.com/channel/UCEzDdNqNkT-7rSfSGSr1hWg', 'Burna Boy', 8900000),
  ('sys_wave', 'UCDfH7E8iHkEjmZ6H9uQ5o1g', 'https://www.youtube.com/channel/UCDfH7E8iHkEjmZ6H9uQ5o1g', 'Uncle Waffles', 410000),
  ('sys_lila', 'UCDfH7E8iHkEjmZ6H9uQ5o1g', 'https://www.youtube.com/channel/UCDfH7E8iHkEjmZ6H9uQ5o1g', 'Uncle Waffles', 410000)
on conflict (artist_id) do nothing;

insert into promotion_campaigns (
  id, creator_id, content_type, external_music_link_id, campaign_name, description, status,
  budget_cents, daily_budget_cents, spent_cents, currency, start_date, end_date,
  target_countries, target_genres, target_audience, featured
) values
  (
    'camp_kwaku', 'sys_ama', 'youtube', 'eml_kwaku',
    'Kwaku nights',
    'Send new listeners to the official video.',
    'active', 15000, 1500, 4200, 'USD', '2026-08-01', '2026-09-15',
    'US,GB,GH', 'Hip Hop', 'new listeners', true
  ),
  (
    'camp_term', 'sys_kofi', 'youtube', 'eml_terminator',
    'Terminator on VerzZify',
    'London to the official clip.',
    'active', 8000, 800, 2100, 'GBP', '2026-08-10', '2026-09-10',
    'GB', 'Hip Hop', 'fans', false
  ),
  (
    'camp_last', 'sys_nia', 'youtube', 'eml_lastlast',
    'Last Last — terrace',
    'Official Burna Boy video, promoted from Nia''s studio.',
    'active', 20000, 2000, 6800, 'USD', '2026-08-05', '2026-09-30',
    'NG,US,GB', 'Afrobeats', 'all', true
  ),
  (
    'camp_tanz', 'sys_lila', 'youtube', 'eml_tanzania',
    'Tanzania — jacaranda season',
    'Official amapiano video.',
    'active', 12000, 1000, 3500, 'ZAR', '2026-08-12', '2026-09-20',
    'ZA,US,GB', 'Amapiano', 'playlist curators', false
  ),
  (
    'camp_ware', 'sys_wave', 'youtube', 'eml_warehouseyt',
    'Warehouse 04 on YouTube',
    'The Accra Wave sending the floor to YouTube.',
    'active', 9000, 900, 1800, 'USD', '2026-08-08', '2026-09-08',
    'GH,US', 'Amapiano', 'fans', false
  ),
  (
    'camp_pending', 'sys_adwoa', 'youtube', 'eml_freemind',
    'Sunday Light clip',
    'Awaiting review.',
    'pending_review', 0, 0, 0, 'USD', '2026-08-20', '2026-09-20',
    'US', 'Gospel', 'fans', false
  )
on conflict (id) do nothing;

insert into promotion_targets (id, campaign_id, target_type, target_value) values
  ('pt_1', 'camp_kwaku', 'country', 'US'),
  ('pt_2', 'camp_kwaku', 'genre', 'Hip Hop'),
  ('pt_3', 'camp_last', 'country', 'NG'),
  ('pt_4', 'camp_last', 'genre', 'Afrobeats'),
  ('pt_5', 'camp_tanz', 'country', 'ZA'),
  ('pt_6', 'camp_tanz', 'genre', 'Amapiano'),
  ('pt_7', 'camp_term', 'country', 'GB'),
  ('pt_8', 'camp_term', 'genre', 'Hip Hop')
on conflict (id) do nothing;

insert into promotion_impressions (id, campaign_id, user_id, created_at) values
  ('imp_1', 'camp_kwaku', null, now() - interval '2 hours'),
  ('imp_2', 'camp_kwaku', null, now() - interval '1 day'),
  ('imp_3', 'camp_kwaku', null, now() - interval '3 days'),
  ('imp_4', 'camp_last', null, now() - interval '5 hours'),
  ('imp_5', 'camp_last', null, now() - interval '2 days'),
  ('imp_6', 'camp_tanz', null, now() - interval '6 hours'),
  ('imp_7', 'camp_term', null, now() - interval '8 hours'),
  ('imp_8', 'camp_ware', null, now() - interval '12 hours')
on conflict (id) do nothing;

insert into promotion_clicks (id, campaign_id, user_id, kind, created_at) values
  ('clk_1', 'camp_kwaku', null, 'play', now() - interval '90 minutes'),
  ('clk_2', 'camp_kwaku', null, 'card', now() - interval '1 day'),
  ('clk_3', 'camp_last', null, 'play', now() - interval '3 hours'),
  ('clk_4', 'camp_last', null, 'profile', now() - interval '2 days'),
  ('clk_5', 'camp_tanz', null, 'play', now() - interval '4 hours'),
  ('clk_6', 'camp_ware', null, 'share', now() - interval '10 hours')
on conflict (id) do nothing;

insert into promotion_engagement (id, campaign_id, user_id, event_name, created_at) values
  ('eng_1', 'camp_kwaku', null, 'playback_open', now() - interval '90 minutes'),
  ('eng_2', 'camp_last', null, 'playback_open', now() - interval '3 hours'),
  ('eng_3', 'camp_last', null, 'profile_visit', now() - interval '2 days'),
  ('eng_4', 'camp_tanz', null, 'playback_open', now() - interval '4 hours'),
  ('eng_5', 'camp_ware', null, 'share', now() - interval '10 hours')
on conflict (id) do nothing;


-- ========== 0005_creator_studio.sql ==========

-- Creator studio extras. Replay-safe.

alter table tracks add column if not exists mood text;

alter table profiles add column if not exists available boolean not null default false;

create table if not exists video_chat_sessions (
  id text primary key,
  artist_id text not null references artist_profiles(user_id),
  fan_id text references profiles(id),
  duration_min integer not null default 15,
  price_cents integer not null default 0,
  currency text not null default 'USD',
  status text not null default 'waiting',
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists video_chat_artist_idx on video_chat_sessions (artist_id, created_at desc);


-- ========== 0006_video_demo.sql ==========

insert into video_chat_sessions (id, artist_id, duration_min, price_cents, currency, status, notes)
values
  ('vc_demo_ama','sys_ama',15,15000,'GHS','waiting','Waiting room — Ama'),
  ('vc_demo_nia','sys_nia',10,22000,'NGN','waiting','Waiting room — Nia')
on conflict (id) do nothing;


-- ========== 0007_global_catalog.sql ==========

-- Global roster. Fictional artists. Replay-safe.

insert into genres (id, name, slug) values
  ('g_citypop','City Pop','city-pop'),
  ('g_electropop','Electropop','electropop'),
  ('g_techno','Techno','techno'),
  ('g_indiepop','Indie Pop','indie-pop')
on conflict (id) do nothing;

insert into profiles (id, username, display_name, role, country, bio, avatar_url, banner_url, city) values
  ('sys_hana','hana-mori','Hana Mori','artist','JP','City pop after midnight in Shibuya rain.','/artists/hana.jpg','/banners/tokyo.jpg','Tokyo'),
  ('sys_mateo','mateo-ruiz','Mateo Ruiz','artist','MX','Latin from a Mexico City rooftop.','/artists/mateo.jpg','/covers/rooftop-chair.jpg','Mexico City'),
  ('sys_nova','nova-park','Nova Park','artist','KR','Seoul electropop, chrome and rain.','/artists/nova.jpg','/banners/seoul.jpg','Seoul'),
  ('sys_priya','priya-sen','Priya Sen','artist','IN','Indie pop through a Mumbai monsoon window.','/artists/priya.jpg','/covers/monsoon-window.jpg','Mumbai'),
  ('sys_luca','luca-voss','Luca Voss','artist','DE','Berlin techno. Concrete, one strobe.','/artists/luca.jpg','/covers/berlin-strobe.jpg','Berlin'),
  ('sys_amira','amira-haddad','Amira Haddad','artist','LB','Beirut dusk, linen, a quiet voice.','/artists/amira.jpg','/covers/beirut-dusk.jpg','Beirut'),
  ('sys_jade','jade-rivera','Jade Rivera','artist','US','Los Angeles R&B at the last light.','/artists/jade.jpg','/covers/palm-shadow.jpg','Los Angeles'),
  ('sys_kenji','kenji-sato','Kenji Sato','producer','JP','Osaka electronics, analog and alley neon.','/artists/kenji.jpg','/covers/osaka-alley.jpg','Osaka')
on conflict (id) do nothing;

insert into artist_profiles (user_id, artist_name, legal_name, verification_status, monthly_listeners, biography, genres, payout_ready) values
  ('sys_hana','Hana Mori','Hana Mori','verified',910000,'Tokyo city pop with patience — neon on wet tar, no hurry in the chorus.','City Pop',true),
  ('sys_mateo','Mateo Ruiz','Mateo Ruiz Herrera','verified',640000,'Rooftop latin from CDMX. Guitar, dust, and a crowd that sings the second verse.','Latin',true),
  ('sys_nova','Nova Park','Park Soo-min','verified',1100000,'Seoul electropop. Tight drums, chrome synths, a voice that does not blink.','Electropop',true),
  ('sys_priya','Priya Sen','Priya Sen','verified',430000,'Mumbai indie pop. Rain on the glass, a lamp left on, the city still awake.','Indie Pop',true),
  ('sys_luca','Luca Voss','Luca Voss','verified',520000,'Berlin techno. One room, one strobe, no vocals until they earn it.','Techno',true),
  ('sys_amira','Amira Haddad','Amira Haddad','verified',310000,'Beirut indie. Arabic and English in the same breath, balcony dusk.','Indie',true),
  ('sys_jade','Jade Rivera','Jade Rivera','verified',780000,'Los Angeles R&B. Palm shadows, late sun, a hook that stays.','R&B',true),
  ('sys_kenji','Kenji Sato','Kenji Sato','pending',145000,'Osaka producer. Vending-machine neon, analog desks, no wasted hits.','Electronic',false)
on conflict (user_id) do nothing;

insert into albums (id, artist_id, title, description, cover_url, release_date, album_type, price_cents, currency) values
  ('alb_cross','sys_hana','Midnight Crossing','City pop for the last train.','/covers/midnight-crossing.jpg','2026-06-14','single',499,'USD'),
  ('alb_chair','sys_mateo','Empty Chair','Latin from a CDMX roof.','/covers/rooftop-chair.jpg','2026-05-28','single',399,'USD'),
  ('alb_glass','sys_nova','Glass Rain','Electropop through Seoul glass.','/covers/seoul-glass.jpg','2026-07-01','ep',799,'USD'),
  ('alb_monsoon','sys_priya','Monsoon Window','Indie pop, rain left on.','/covers/monsoon-window.jpg','2026-04-22','single',0,'USD'),
  ('alb_strobe','sys_luca','One Strobe','A Berlin floor, nothing extra.','/covers/berlin-strobe.jpg','2026-03-09','single',499,'EUR'),
  ('alb_dusk','sys_amira','Balcony Dusk','Beirut evening, two languages.','/covers/beirut-dusk.jpg','2026-02-14','single',0,'USD'),
  ('alb_palm','sys_jade','Palm Shadow','R&B at the last Los Angeles light.','/covers/palm-shadow.jpg','2026-06-20','single',399,'USD'),
  ('alb_alley','sys_kenji','Alley Neon','Instrumentals from Osaka night.','/covers/osaka-alley.jpg','2026-05-11','single',299,'USD')
on conflict (id) do nothing;

insert into tracks (
  id, artist_id, album_id, title, cover_url, audio_url, duration_ms, genre, language,
  distribution, price_cents, currency, copyright_owner, producer, songwriter, play_count, like_count, sort_order, country, status
) values
  ('trk_13','sys_hana','alb_cross','Midnight Crossing','/covers/midnight-crossing.jpg','/audio/t01.mp3',75000,'City Pop','Japanese','paid_download',499,'USD','Hana Mori','Kenji Sato','Hana Mori',268000,6400,1,'JP','published'),
  ('trk_14','sys_hana','alb_cross','Last Train','/covers/midnight-crossing.jpg','/audio/t02.mp3',75000,'City Pop','Japanese','free_stream',0,'USD','Hana Mori','Kenji Sato','Hana Mori',141000,3200,2,'JP','published'),
  ('trk_15','sys_mateo','alb_chair','Empty Chair','/covers/rooftop-chair.jpg','/audio/t03.mp3',75000,'Latin','Spanish','paid_download',399,'USD','Mateo Ruiz','Mateo Ruiz','Mateo Ruiz',198000,4100,1,'MX','published'),
  ('trk_16','sys_nova','alb_glass','Glass Rain','/covers/seoul-glass.jpg','/audio/t04.mp3',75000,'Electropop','Korean','premium',799,'USD','Nova Park','Nova Park','Nova Park',388000,9100,1,'KR','published'),
  ('trk_17','sys_nova','alb_glass','Chrome','/covers/seoul-glass.jpg','/audio/t05.mp3',75000,'Electropop','Korean','free_stream',0,'USD','Nova Park','Nova Park','Nova Park',221000,5400,2,'KR','published'),
  ('trk_18','sys_priya','alb_monsoon','Monsoon Window','/covers/monsoon-window.jpg','/audio/t06.mp3',75000,'Indie Pop','English','free_download',0,'USD','Priya Sen','Priya Sen','Priya Sen',112000,2800,1,'IN','published'),
  ('trk_19','sys_luca','alb_strobe','One Strobe','/covers/berlin-strobe.jpg','/audio/t07.mp3',75000,'Techno','Instrumental','paid_download',499,'EUR','Luca Voss','Luca Voss','Luca Voss',156000,2900,1,'DE','published'),
  ('trk_20','sys_amira','alb_dusk','Balcony Dusk','/covers/beirut-dusk.jpg','/audio/t08.mp3',75000,'Indie','Arabic','free_download',0,'USD','Amira Haddad','Amira Haddad','Amira Haddad',94000,2100,1,'LB','published'),
  ('trk_21','sys_jade','alb_palm','Palm Shadow','/covers/palm-shadow.jpg','/audio/t09.mp3',75000,'R&B','English','paid_download',399,'USD','Jade Rivera','Ebo Darko','Jade Rivera',274000,6700,1,'US','published'),
  ('trk_22','sys_kenji','alb_alley','Alley Neon','/covers/osaka-alley.jpg','/audio/t10.mp3',75000,'Electronic','Instrumental','free_stream',0,'USD','Kenji Sato','Kenji Sato','Kenji Sato',67000,1400,1,'JP','published')
on conflict (id) do nothing;

insert into playlists (id, user_id, title, description, cover_url, is_public, is_system, kind) values
  ('pl_latin','sys_zelyro','Latin Now','Rooftops, second verses, no translation needed.','/covers/rooftop-chair.jpg',true,true,'editorial'),
  ('pl_city','sys_zelyro','City Pop After Dark','Tokyo midnight, last trains.','/covers/midnight-crossing.jpg',true,true,'editorial'),
  ('pl_electro','sys_zelyro','Electronic','Seoul chrome to Berlin concrete.','/covers/berlin-strobe.jpg',true,true,'editorial'),
  ('pl_pop','sys_zelyro','Pop Worldwide','Hooks from more than one city.','/covers/seoul-glass.jpg',true,true,'editorial')
on conflict (id) do nothing;

insert into playlist_tracks (playlist_id, track_id, position) values
  ('pl_ghana','trk_16',7),('pl_ghana','trk_13',8),('pl_ghana','trk_21',9),('pl_ghana','trk_15',10),
  ('pl_latin','trk_15',1),
  ('pl_city','trk_13',1),('pl_city','trk_14',2),
  ('pl_electro','trk_16',1),('pl_electro','trk_17',2),('pl_electro','trk_19',3),('pl_electro','trk_22',4),
  ('pl_pop','trk_16',1),('pl_pop','trk_21',2),('pl_pop','trk_13',3),('pl_pop','trk_18',4),
  ('pl_free','trk_18',4),('pl_free','trk_20',5),
  ('pl_hip','trk_21',4)
on conflict do nothing;

insert into events (id, organizer_id, title, poster_url, venue, city, country, starts_at, description, status) values
  ('evt_shibuya','sys_hana','Midnight Crossing — Live','/covers/midnight-crossing.jpg','Circle Line Hall','Tokyo','JP','2026-09-20 19:30:00+00','City pop, last-train encore.','published'),
  ('evt_roma','sys_mateo','Rooftop Session CDMX','/covers/rooftop-chair.jpg','Roma Norte Roof','Mexico City','MX','2026-09-08 20:00:00+00','Latin, dust, and the second verse.','published'),
  ('evt_han','sys_nova','Glass Rain','/covers/seoul-glass.jpg','Han River Warehouse','Seoul','KR','2026-09-26 21:00:00+00','Electropop under rain glass.','published'),
  ('evt_kraft','sys_luca','One Strobe','/covers/berlin-strobe.jpg','Kraftwerk Room','Berlin','DE','2026-09-14 23:00:00+00','Techno until the strobe fails.','published'),
  ('evt_echo','sys_jade','Palm Shadow Night','/covers/palm-shadow.jpg','Echo Park Loft','Los Angeles','US','2026-09-11 21:00:00+00','R&B at the last light.','published')
on conflict (id) do nothing;

insert into event_ticket_types (id, event_id, name, price_cents, currency, capacity, sold) values
  ('tt_shi_std','evt_shibuya','Standard',4500,'USD',400,156),
  ('tt_roma_std','evt_roma','Standard',1800,'USD',220,88),
  ('tt_han_std','evt_han','Standard',3800,'USD',500,241),
  ('tt_kft_std','evt_kraft','Standard',2200,'EUR',300,190),
  ('tt_echo_std','evt_echo','Standard',2500,'USD',180,71)
on conflict (id) do nothing;

insert into live_events (id, artist_id, title, poster_url, description, starts_at, price_cents, is_free, capacity, status) values
  ('live_nova','sys_nova','Glass Rain — VerzZify Live','/covers/seoul-glass.jpg','PPV from Seoul. Server-validated access.','2026-08-28 13:00:00+00',1200,false,800,'scheduled'),
  ('live_hana','sys_hana','Last Train — Tokyo','/covers/midnight-crossing.jpg','A free midnight set from Tokyo.','2026-08-30 15:00:00+00',0,true,null,'scheduled')
on conflict (id) do nothing;

insert into video_call_services (artist_id, duration_min, price_cents, currency, available) values
  ('sys_hana',15,2500,'USD',true),
  ('sys_nova',10,3000,'USD',true),
  ('sys_jade',15,2000,'USD',true),
  ('sys_mateo',15,1500,'USD',true)
on conflict (artist_id) do nothing;

insert into posts (id, user_id, body, image_url, track_id, like_count, created_at) values
  ('post_7','sys_hana','Midnight Crossing is out. If you are on the last train, this is the one.','/covers/midnight-crossing.jpg','trk_13',964, now() - interval '6 hours'),
  ('post_8','sys_nova','Glass Rain, Seoul. PPV this week on VerzZify Live.','/covers/seoul-glass.jpg','trk_16',1502, now() - interval '12 hours'),
  ('post_9','sys_mateo','Empty chair, full roof. CDMX Thursday.','/covers/rooftop-chair.jpg','trk_15',411, now() - interval '2 days'),
  ('post_10','sys_jade','Palm Shadow. Los Angeles does not owe you a sunset, but this one stayed.','/covers/palm-shadow.jpg','trk_21',733, now() - interval '4 hours')
on conflict (id) do nothing;

insert into articles (id, title, slug, category, excerpt, body, cover_url) values
  ('art_3','A catalog with more than one city','catalog-more-than-one-city','Music','Tokyo, Seoul, Mexico City, Berlin, Lagos, London — same house.','VerzZify is not a regional streaming app. The point is ownership: an artist in Seoul can sell a file, an artist in Accra can sell a ticket, an artist in Los Angeles can promote an official YouTube without the catalog confusing the two. The cities are the catalog, not the brand.','/covers/seoul-glass.jpg')
on conflict (id) do nothing;

insert into wallets (user_id, currency) values
  ('sys_hana','USD'),('sys_mateo','USD'),('sys_nova','USD'),('sys_priya','USD'),
  ('sys_luca','EUR'),('sys_amira','USD'),('sys_jade','USD'),('sys_kenji','USD')
on conflict (user_id) do nothing;

insert into ledger_entries (id, wallet_user_id, amount_cents, direction, kind, ref_type, available, meta) values
  ('led_nova_1','sys_nova',388000,'credit','sale','track',true,'{"note":"lifetime seed"}'),
  ('led_hana_1','sys_hana',142000,'credit','sale','track',true,'{"note":"lifetime seed"}'),
  ('led_jade_1','sys_jade',98000,'credit','sale','track',true,'{"note":"lifetime seed"}')
on conflict (id) do nothing;

insert into studios (id, name, city, country, kind, description) values
  ('st_shibuya', 'Shibuya Night Desk', 'Tokyo', 'JP', 'recording', 'After-hours booth, wet street below.'),
  ('st_itaewon', 'Han River Glass', 'Seoul', 'KR', 'recording', 'Tracking with city rain on the pane.'),
  ('st_roma', 'Roma Norte Roof', 'Mexico City', 'MX', 'rehearsal', 'Open air, terracotta, late light.'),
  ('st_kraft', 'Kraftwerk Room', 'Berlin', 'DE', 'rehearsal', 'Concrete, one strobe, no wasted hits.'),
  ('st_echo', 'Echo Park Loft', 'Los Angeles', 'US', 'recording', 'Palm shadow on the south wall.')
on conflict (id) do nothing;

insert into producer_profiles (user_id, display_title, beats, services, credits, location, available_for_collab, youtube_url, contact)
values (
  'sys_kenji',
  'Osaka electronics, analog and alley neon',
  'Synth beds, city-pop drums, night-market FX',
  'Beat lease, mix, soundtrack cue',
  'Hana Mori — Midnight Crossing',
  'Osaka',
  true,
  'https://youtube.com/@verzzify',
  'kenji@verzzify.com'
) on conflict (user_id) do nothing;

update remote_config set value = 'USD,GBP,EUR,JPY,KRW,MXN,INR,GHS,NGN,ZAR,BRL'
  where key = 'supported_currencies';


-- ========== 0008_charts.sql ==========

-- Global Music Charts: weekly snapshots for movement (▲ ▼ NEW).
-- Live ranking is computed from streams + saves. Snapshots are last week.

create table if not exists chart_snapshots (
  id text primary key,
  chart_key text not null,
  period text not null default 'weekly',
  captured_at timestamptz not null default now()
);

create index if not exists chart_snapshots_key_idx on chart_snapshots (chart_key, captured_at desc);

create table if not exists chart_ranks (
  snapshot_id text not null references chart_snapshots(id) on delete cascade,
  position integer not null,
  item_type text not null,
  item_id text not null,
  points integer not null default 0,
  primary key (snapshot_id, item_type, item_id)
);

insert into chart_snapshots (id, chart_key, period, captured_at) values
  ('snap_tracks_global', 'tracks:global:all', 'weekly', now() - interval '7 days'),
  ('snap_artists_global', 'artists:global:all', 'weekly', now() - interval '7 days')
on conflict (id) do nothing;

-- Previous week: a few swaps so the live board shows rises, drops, and NEW.
insert into chart_ranks (snapshot_id, position, item_type, item_id, points) values
  ('snap_tracks_global', 1, 'track', 'trk_04', 490000),
  ('snap_tracks_global', 2, 'track', 'trk_13', 350000),
  ('snap_tracks_global', 3, 'track', 'trk_05', 310000),
  ('snap_tracks_global', 4, 'track', 'trk_16', 300000),
  ('snap_tracks_global', 5, 'track', 'trk_10', 265000),
  ('snap_tracks_global', 6, 'track', 'trk_01', 230000),
  ('snap_tracks_global', 7, 'track', 'trk_21', 210000),
  ('snap_tracks_global', 8, 'track', 'trk_07', 205000),
  ('snap_tracks_global', 9, 'track', 'trk_03', 120000),
  ('snap_tracks_global', 10, 'track', 'trk_02', 150000),
  ('snap_tracks_global', 11, 'track', 'trk_08', 118000),
  ('snap_tracks_global', 12, 'track', 'trk_19', 140000),
  ('snap_tracks_global', 13, 'track', 'trk_12', 110000),
  ('snap_tracks_global', 14, 'track', 'trk_09', 90000),
  ('snap_tracks_global', 15, 'track', 'trk_06', 82000),
  ('snap_tracks_global', 16, 'track', 'trk_11', 55000),
  ('snap_artists_global', 1, 'artist', 'sys_nia', 1200000),
  ('snap_artists_global', 2, 'artist', 'sys_hana', 900000),
  ('snap_artists_global', 3, 'artist', 'sys_ama', 840000),
  ('snap_artists_global', 4, 'artist', 'sys_nova', 700000),
  ('snap_artists_global', 5, 'artist', 'sys_lila', 670000),
  ('snap_artists_global', 6, 'artist', 'sys_kofi', 510000),
  ('snap_artists_global', 7, 'artist', 'sys_wave', 390000),
  ('snap_artists_global', 8, 'artist', 'sys_adwoa', 276000),
  ('snap_artists_global', 9, 'artist', 'sys_zainab', 221000),
  ('snap_artists_global', 10, 'artist', 'sys_sefu', 188000),
  ('snap_artists_global', 11, 'artist', 'sys_yaw', 154000),
  ('snap_artists_global', 12, 'artist', 'sys_ebo', 98000)
on conflict do nothing;


-- ========== 0009_global_200.sql ==========

-- VerzZify Global 200: Billboard-style stream-equivalent units.
-- SEU = (paid downloads × 200) + streams. D2C sales on VerzZify count.

create table if not exists chart_download_units (
  track_id text primary key references tracks(id) on delete cascade,
  units integer not null default 0
);

insert into chart_download_units (track_id, units) values
  ('trk_16', 920),
  ('trk_04', 210),
  ('trk_21', 440),
  ('trk_13', 380),
  ('trk_15', 120),
  ('trk_05', 40),
  ('trk_17', 85),
  ('trk_10', 60),
  ('trk_01', 90),
  ('trk_07', 55),
  ('trk_19', 70),
  ('trk_14', 30),
  ('trk_03', 45),
  ('trk_18', 22),
  ('trk_08', 15),
  ('trk_20', 18),
  ('trk_09', 28),
  ('trk_22', 12),
  ('trk_06', 8),
  ('trk_11', 10),
  ('trk_02', 14),
  ('trk_12', 11)
on conflict (track_id) do update set units = excluded.units;

alter table chart_ranks add column if not exists peak integer;
alter table chart_ranks add column if not exists weeks_on integer;

update chart_ranks set
  peak = case item_id
    when 'trk_04' then 1 when 'trk_13' then 2 when 'trk_16' then 1 when 'trk_21' then 3
    when 'trk_05' then 3 when 'trk_10' then 5 when 'trk_01' then 4 when 'trk_07' then 6
    else position end,
  weeks_on = case item_id
    when 'trk_04' then 18 when 'trk_13' then 9 when 'trk_16' then 7 when 'trk_21' then 6
    when 'trk_05' then 16 when 'trk_10' then 14 when 'trk_01' then 22 when 'trk_07' then 11
    when 'trk_03' then 8 when 'trk_19' then 5 when 'sys_nia' then 22 when 'sys_nova' then 7
    when 'sys_hana' then 9 when 'sys_ama' then 22 else 4 end
where peak is null or weeks_on is null;

insert into chart_snapshots (id, chart_key, period, captured_at) values
  ('snap_tracks_excl_us', 'tracks:excl_us:all', 'weekly', now() - interval '7 days')
on conflict (id) do nothing;

insert into chart_ranks (snapshot_id, position, item_type, item_id, points, peak, weeks_on)
select 'snap_tracks_excl_us',
       row_number() over (order by position),
       item_type, item_id, points, peak, weeks_on
from chart_ranks
where snapshot_id = 'snap_tracks_global'
  and item_id not in ('trk_21', 'trk_08', 'trk_11')
on conflict do nothing;


-- ========== 0010_storage.sql ==========

-- Object store index: AWS S3 in production, local disk in preview.
-- Masters stay private. Stream + public are served via /api/storage/media/:id.

create table if not exists media_objects (
  id text primary key,
  owner_id text not null references profiles(id) on delete cascade,
  bucket text not null,
  bucket_kind text not null,
  object_key text not null,
  mime text not null,
  size_bytes integer not null default 0,
  kind text not null,
  status text not null default 'pending',
  public_url text,
  upload_token text unique,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  unique (bucket, object_key)
);

create index if not exists media_objects_owner_idx on media_objects (owner_id, created_at desc);
create index if not exists media_objects_token_idx on media_objects (upload_token)
  where upload_token is not null;


-- ========== 0011_guest.sql ==========

-- Guest creator used while sign-in is off (id matches Better Auth DEV_USER_ID).

insert into profiles (id, username, display_name, role, country, bio, avatar_url, banner_url, city)
values (
  'dev-user',
  'you',
  'You',
  'artist',
  'US',
  'Guest creator. Accounts come later.',
  '/favicon.svg',
  '/banners/hero.jpg',
  null
)
on conflict (id) do nothing;

insert into artist_profiles (user_id, artist_name, verification_status, biography, genres, payout_ready)
values (
  'dev-user',
  'You',
  'verified',
  'Open Studio and upload. Sign-in returns when accounts ship.',
  'Pop',
  false
)
on conflict (user_id) do nothing;

insert into wallets (user_id, currency) values ('dev-user', 'USD')
on conflict do nothing;


-- ========== 0012_mack_profile.sql ==========

-- Audiomack-style guest profile: banner, portrait, uploads, social graph.

update profiles set
  display_name = 'You',
  bio = 'Lisbon nights, coral mix, songs I actually own. Guest creator while accounts are off.',
  avatar_url = '/artists/you.jpg',
  banner_url = '/banners/you.jpg',
  city = 'Lisbon',
  country = 'PT',
  favorite_genres = 'Alt-Pop, Electronic'
where id = 'dev-user';

update artist_profiles set
  artist_name = 'You',
  verification_status = 'verified',
  monthly_listeners = 184200,
  biography = 'Lisbon nights, coral mix, songs I actually own. Guest creator while accounts are off.',
  genres = 'Alt-Pop, Electronic',
  socials = 'instagram youtube'
where user_id = 'dev-user';

insert into albums (id, artist_id, title, description, cover_url, release_date, album_type, price_cents, currency)
values
  ('alb_you_hour', 'dev-user', 'Glass Hour', 'A single cut for late rooms.', '/covers/glass-hour.jpg', '2026-07-22', 'single', 0, 'USD'),
  ('alb_you_wire', 'dev-user', 'Afterglow Wire', 'Wet streets, one take vocal.', '/covers/afterglow-wire.jpg', '2026-08-04', 'single', 199, 'USD')
on conflict (id) do nothing;

insert into tracks (
  id, artist_id, album_id, title, cover_url, audio_url, duration_ms, genre, language,
  distribution, price_cents, currency, producer, songwriter, copyright_owner,
  play_count, like_count, sort_order, country, status
) values
  ('trk_you_1', 'dev-user', 'alb_you_hour', 'Glass Hour', '/covers/glass-hour.jpg', '/audio/t10.mp3', 188000, 'Electropop', 'English', 'free_stream', 0, 'USD', 'You', 'You', 'You', 76257, 494, 1, 'PT', 'published'),
  ('trk_you_2', 'dev-user', 'alb_you_wire', 'Afterglow Wire', '/covers/afterglow-wire.jpg', '/audio/t12.mp3', 204000, 'Alt-Pop', 'English', 'paid_download', 199, 'USD', 'You', 'You', 'You', 41880, 338, 2, 'PT', 'published')
on conflict (id) do nothing;

insert into follows (follower_id, following_id) values
  ('dev-user', 'sys_nova'),
  ('dev-user', 'sys_hana'),
  ('dev-user', 'sys_jade'),
  ('sys_nova', 'dev-user'),
  ('sys_hana', 'dev-user'),
  ('sys_mateo', 'dev-user'),
  ('sys_kenji', 'dev-user')
on conflict do nothing;

insert into favorites (user_id, target_type, target_id) values
  ('dev-user', 'track', 'trk_16'),
  ('dev-user', 'track', 'trk_01'),
  ('dev-user', 'track', 'trk_21'),
  ('dev-user', 'track', 'trk_you_1')
on conflict do nothing;

insert into playlists (id, user_id, title, description, cover_url, is_public, is_system, kind)
values ('pl_you_late', 'dev-user', 'Late rooms', 'What I play after one in the morning.', '/covers/glass-hour.jpg', true, false, 'custom')
on conflict (id) do nothing;

insert into playlist_tracks (playlist_id, track_id, position) values
  ('pl_you_late', 'trk_you_1', 0),
  ('pl_you_late', 'trk_you_2', 1),
  ('pl_you_late', 'trk_16', 2)
on conflict do nothing;

insert into posts (id, user_id, body, image_url, track_id, like_count, created_at) values
  ('post_you_1', 'dev-user', 'Glass Hour is up. Free to stream, mine to keep.', '/covers/glass-hour.jpg', 'trk_you_1', 88, now() - interval '1 day'),
  ('post_you_2', 'dev-user', 'Afterglow Wire — paid download if you want the file.', '/covers/afterglow-wire.jpg', 'trk_you_2', 41, now() - interval '6 hours')
on conflict (id) do nothing;


-- ========== 0013_profile_live.sql ==========

-- Live set + 1-1 for the guest profile (Audiomack-plus house).

insert into live_events (id, artist_id, title, poster_url, description, starts_at, price_cents, is_free, capacity, status)
values (
  'live_you_wire',
  'dev-user',
  'Afterglow Wire — VerzZify Live',
  '/banners/you.jpg',
  'Lisbon rooftop, one take, coral mix. PPV on VerzZify Live.',
  now() + interval '2 days',
  900,
  false,
  400,
  'scheduled'
)
on conflict (id) do nothing;

insert into video_call_services (artist_id, duration_min, price_cents, currency, available)
values ('dev-user', 15, 2500, 'USD', true)
on conflict (artist_id) do nothing;


-- ========== 0014_verzzify.sql ==========

-- Swap leftover Zelyro copy to VerzZify on already-applied catalogs.

update live_events
set title = replace(title, 'Zelyro', 'VerzZify'),
    description = replace(coalesce(description, ''), 'Zelyro', 'VerzZify')
where title like '%Zelyro%' or coalesce(description, '') like '%Zelyro%';

update posts
set body = replace(body, 'Zelyro', 'VerzZify')
where body like '%Zelyro%';

update articles
set title = replace(title, 'Zelyro', 'VerzZify'),
    excerpt = replace(coalesce(excerpt, ''), 'Zelyro', 'VerzZify'),
    body = replace(coalesce(body, ''), 'Zelyro', 'VerzZify')
where title like '%Zelyro%'
   or coalesce(excerpt, '') like '%Zelyro%'
   or coalesce(body, '') like '%Zelyro%';

update subscription_plans
set name = replace(name, 'Zelyro', 'VerzZify'),
    features = replace(coalesce(features, ''), 'Zelyro', 'VerzZify')
where name like '%Zelyro%' or coalesce(features, '') like '%Zelyro%';

update profiles
set username = 'verzzify',
    display_name = 'VerzZify',
    bio = replace(coalesce(bio, ''), 'Zelyro', 'VerzZify')
where id = 'sys_zelyro';

update feature_flags
set key = 'ENABLE_VERZZIFY_LIVE'
where key = 'ENABLE_ZELYRO_LIVE';

