/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppChartsRouteImport } from './routes/_app/charts'
import { Route as AppCommunityRouteImport } from './routes/_app/community'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppNewsRouteImport } from './routes/_app/news'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppStudioRouteImport } from './routes/_app/studio'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiInfraRouteImport } from './routes/api/infra'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as AppAlbumIdRouteImport } from './routes/_app/album.$id'
import { Route as AppArtistSlugRouteImport } from './routes/_app/artist.$slug'
import { Route as AppEventIdRouteImport } from './routes/_app/event.$id'
import { Route as AppLiveIdRouteImport } from './routes/_app/live.$id'
import { Route as AppPlaylistIdRouteImport } from './routes/_app/playlist.$id'
import { Route as AppTrackIdRouteImport } from './routes/_app/track.$id'
import { Route as AppVideoIdRouteImport } from './routes/_app/video.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'
import { Route as ApiStorageMediaIdRouteImport } from './routes/api/storage/media.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppChartsRoute = AppChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInfraRoute = ApiInfraRouteImport.update({
  id: '/api/infra',
  path: '/api/infra',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAlbumIdRoute = AppAlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppArtistSlugRoute = AppArtistSlugRouteImport.update({
  id: '/artist/$slug',
  path: '/artist/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppEventIdRoute = AppEventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveIdRoute = AppLiveIdRouteImport.update({
  id: '/live/$id',
  path: '/live/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaylistIdRoute = AppPlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackIdRoute = AppTrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppVideoIdRoute = AppVideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageMediaIdRoute = ApiStorageMediaIdRouteImport.update({
  id: '/api/storage/media/$id',
  path: '/api/storage/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/architecture': typeof ArchitectureRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AppAdminRoute
  '/charts': typeof AppChartsRoute
  '/community': typeof AppCommunityRoute
  '/discover': typeof AppDiscoverRoute
  '/library': typeof AppLibraryRoute
  '/news': typeof AppNewsRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/studio': typeof AppStudioRoute
  '/api/health': typeof ApiHealthRoute
  '/api/infra': typeof ApiInfraRoute
  '/api/rtc': typeof ApiRtcRoute
  '/album/$id': typeof AppAlbumIdRoute
  '/artist/$slug': typeof AppArtistSlugRoute
  '/event/$id': typeof AppEventIdRoute
  '/live/$id': typeof AppLiveIdRoute
  '/playlist/$id': typeof AppPlaylistIdRoute
  '/track/$id': typeof AppTrackIdRoute
  '/video/$id': typeof AppVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/storage/media/$id': typeof ApiStorageMediaIdRoute
}
export interface FileRoutesByTo {
  '/architecture': typeof ArchitectureRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof AppAdminRoute
  '/charts': typeof AppChartsRoute
  '/community': typeof AppCommunityRoute
  '/discover': typeof AppDiscoverRoute
  '/library': typeof AppLibraryRoute
  '/news': typeof AppNewsRoute
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/studio': typeof AppStudioRoute
  '/api/health': typeof ApiHealthRoute
  '/api/infra': typeof ApiInfraRoute
  '/api/rtc': typeof ApiRtcRoute
  '/': typeof AppIndexRoute
  '/album/$id': typeof AppAlbumIdRoute
  '/artist/$slug': typeof AppArtistSlugRoute
  '/event/$id': typeof AppEventIdRoute
  '/live/$id': typeof AppLiveIdRoute
  '/playlist/$id': typeof AppPlaylistIdRoute
  '/track/$id': typeof AppTrackIdRoute
  '/video/$id': typeof AppVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/storage/media/$id': typeof ApiStorageMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/charts': typeof AppChartsRoute
  '/_app/community': typeof AppCommunityRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/news': typeof AppNewsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/studio': typeof AppStudioRoute
  '/api/health': typeof ApiHealthRoute
  '/api/infra': typeof ApiInfraRoute
  '/api/rtc': typeof ApiRtcRoute
  '/_app/': typeof AppIndexRoute
  '/_app/album/$id': typeof AppAlbumIdRoute
  '/_app/artist/$slug': typeof AppArtistSlugRoute
  '/_app/event/$id': typeof AppEventIdRoute
  '/_app/live/$id': typeof AppLiveIdRoute
  '/_app/playlist/$id': typeof AppPlaylistIdRoute
  '/_app/track/$id': typeof AppTrackIdRoute
  '/_app/video/$id': typeof AppVideoIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
  '/api/storage/media/$id': typeof ApiStorageMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/legal'
    | '/login'
    | '/welcome'
    | '/admin'
    | '/charts'
    | '/community'
    | '/discover'
    | '/library'
    | '/news'
    | '/profile'
    | '/search'
    | '/studio'
    | '/api/health'
    | '/api/infra'
    | '/api/rtc'
    | '/album/$id'
    | '/artist/$slug'
    | '/event/$id'
    | '/live/$id'
    | '/playlist/$id'
    | '/track/$id'
    | '/video/$id'
    | '/api/auth/$'
    | '/api/storage/upload'
    | '/api/storage/media/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/architecture'
    | '/legal'
    | '/login'
    | '/welcome'
    | '/admin'
    | '/charts'
    | '/community'
    | '/discover'
    | '/library'
    | '/news'
    | '/profile'
    | '/search'
    | '/studio'
    | '/api/health'
    | '/api/infra'
    | '/api/rtc'
    | '/'
    | '/album/$id'
    | '/artist/$slug'
    | '/event/$id'
    | '/live/$id'
    | '/playlist/$id'
    | '/track/$id'
    | '/video/$id'
    | '/api/auth/$'
    | '/api/storage/upload'
    | '/api/storage/media/$id'
  id:
    | '__root__'
    | '/_app'
    | '/architecture'
    | '/legal'
    | '/login'
    | '/welcome'
    | '/_app/admin'
    | '/_app/charts'
    | '/_app/community'
    | '/_app/discover'
    | '/_app/library'
    | '/_app/news'
    | '/_app/profile'
    | '/_app/search'
    | '/_app/studio'
    | '/api/health'
    | '/api/infra'
    | '/api/rtc'
    | '/_app/'
    | '/_app/album/$id'
    | '/_app/artist/$slug'
    | '/_app/event/$id'
    | '/_app/live/$id'
    | '/_app/playlist/$id'
    | '/_app/track/$id'
    | '/_app/video/$id'
    | '/api/auth/$'
    | '/api/storage/upload'
    | '/api/storage/media/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInfraRoute: typeof ApiInfraRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
  ApiStorageMediaIdRoute: typeof ApiStorageMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/charts': {
      id: '/_app/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof AppChartsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news': {
      id: '/_app/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/studio': {
      id: '/_app/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/infra': {
      id: '/api/infra'
      path: '/api/infra'
      fullPath: '/api/infra'
      preLoaderRoute: typeof ApiInfraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/album/$id': {
      id: '/_app/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AppAlbumIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/artist/$slug': {
      id: '/_app/artist/$slug'
      path: '/artist/$slug'
      fullPath: '/artist/$slug'
      preLoaderRoute: typeof AppArtistSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/event/$id': {
      id: '/_app/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof AppEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live/$id': {
      id: '/_app/live/$id'
      path: '/live/$id'
      fullPath: '/live/$id'
      preLoaderRoute: typeof AppLiveIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playlist/$id': {
      id: '/_app/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof AppPlaylistIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/track/$id': {
      id: '/_app/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof AppTrackIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/video/$id': {
      id: '/_app/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof AppVideoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/media/$id': {
      id: '/api/storage/media/$id'
      path: '/api/storage/media/$id'
      fullPath: '/api/storage/media/$id'
      preLoaderRoute: typeof ApiStorageMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppChartsRoute: typeof AppChartsRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNewsRoute: typeof AppNewsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppStudioRoute: typeof AppStudioRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAlbumIdRoute: typeof AppAlbumIdRoute
  AppArtistSlugRoute: typeof AppArtistSlugRoute
  AppEventIdRoute: typeof AppEventIdRoute
  AppLiveIdRoute: typeof AppLiveIdRoute
  AppPlaylistIdRoute: typeof AppPlaylistIdRoute
  AppTrackIdRoute: typeof AppTrackIdRoute
  AppVideoIdRoute: typeof AppVideoIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppChartsRoute: AppChartsRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNewsRoute: AppNewsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppStudioRoute: AppStudioRoute,
  AppIndexRoute: AppIndexRoute,
  AppAlbumIdRoute: AppAlbumIdRoute,
  AppArtistSlugRoute: AppArtistSlugRoute,
  AppEventIdRoute: AppEventIdRoute,
  AppLiveIdRoute: AppLiveIdRoute,
  AppPlaylistIdRoute: AppPlaylistIdRoute,
  AppTrackIdRoute: AppTrackIdRoute,
  AppVideoIdRoute: AppVideoIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInfraRoute: ApiInfraRoute,
  ApiRtcRoute: ApiRtcRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
  ApiStorageMediaIdRoute: ApiStorageMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
